"""expence table added

Revision ID: 7191f4a57234
Revises: eb2049249644
Create Date: 2024-12-14 18:59:16.215961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7191f4a57234'
down_revision: Union[str, None] = 'eb2049249644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('expence_type', sa.Enum('Travel', 'Component', 'Other', name='expencetype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('is_declined', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expence_expence_type'), 'expence', ['expence_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expence_expence_type'), table_name='expence')
    op.drop_table('expence')
    # ### end Alembic commands ###
