"""device_id unique constraint removed from user_sessions table

Revision ID: b739cb69368c
Revises: 270b9dbc2086
Create Date: 2024-11-27 20:21:29.934695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b739cb69368c'
down_revision: Union[str, None] = '270b9dbc2086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_sessions_device_id_key', 'user_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_sessions_device_id_key', 'user_sessions', ['device_id'])
    # ### end Alembic commands ###
